django/python_beltreview/apps/login/urls.py
from django.conf.urls import url
from views import *
# from django.contrib import admin

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'registration'),
    url(r'^success$', success, name = 'success'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout')
    # url(r'^admin/', admin.site.urls),
]

django/python_beltreview/beltreviewer/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login.urls', namespace= 'users')),
    url(r'^books/', include('apps.books.urls', namespace='books')),
] 

django/python_beltreview/apps/login/models.py
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
import bcrypt
import re


EMAIL_REGEX = re.compile (r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.

class UserManager(models.Manager):
    def valid_registration(self, user_info, request):
        valid = True
        if not user_info['first_name'].isalpha():
            messages.warning(request, "First name must be all letters!")
            valid = False
        if len(user_info['first_name']) < 2:
            messages.warning(request, "First name must be 2 or more characters long!")
            valid = False
        if not user_info['last_name'].isalpha():
            messages.warning(request, "Last name must be all letters!")
            valid = False
        if len(user_info['last_name']) < 2:
            messages.warning(request, "Last name must be 2 or more characters long!")
            valid = False
        if not EMAIL_REGEX.match(user_info['email_address']):
            messages.warning(request, "Email is not a valid email!")
            valid = False
        if len(user_info['password']) < 7:
            messages.warning(request, "Password is too short!")
            valid = False
        if user_info['password'] != user_info['confirm_password']:
            messages.warning(request, "Passwords do not match!")
            valid = False
        if User.objects.filter(email = user_info['email_address']):
            messages.error(request, "This Email already exists!")
            valid = False
        if valid == True:
            # messages.success(request, "Successful registration, " + user_info['first_name'] + "!")
            hashed = bcrypt.hashpw(user_info['password'].encode(), bcrypt.gensalt())
            User.objects.create(first_name = request.POST['first_name'], last_name = request.POST['last_name'], email = request.POST['email_address'], password = hashed)
        return valid

    def exisiting_user(self, user_info, request):
        valid = True
        if User.objects.filter(email = user_info['email_address']):
            hashed = User.objects.get(email = user_info['email_address']).password
            hashed = hashed.encode('utf-8')
            password = user_info['password']
            password = password.encode('utf-8')
            if bcrypt.hashpw(password, hashed) == hashed:
                # messages.success(request, "Success! Welcome back, " + User.objects.get(email = user_info['email_address']).first_name + "!")
                valid = True
            else:
                messages.warning(request, "Incorrect password!")
                valid = False
        else:
            messages.warning(request, "Your email is not correct!")
            valid = False
        return valid

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField()
    password = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    UserManager = UserManager()
    objects = models.Manager()

django/python_beltreview/apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'first_name' not in request.session:
        return render(request, 'login/index.html')
    else:
        return render(request, 'books/home.html')

def register(request):
    if User.UserManager.valid_registration(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['user_id'] = user.id
        return redirect(reverse('books:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def success(request):
    return render(request, 'books/home.html')

def login(request):
    if User.UserManager.exisiting_user(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['email_address'] = user.last_name
        request.session['user_id'] = user.id
        return redirect(reverse('books:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('users:index'))

django/python_beltreview/apps/login/templates/login/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration | Home </title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Hello, welcome to Review Books!</h1>
        <p>Please register or login below!</p>
      </div>
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
        {% endfor %}
      {% endif %}

      <h2>Login</h2>
      <form class="form-horizontal" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="email_address" class="col-sm-2 control-label">Email Address</label>
          <div class="col-sm-6">
            <input type="email" name="email_address" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <label for="password" class="col-sm-2 control-label">Password</label>
          <div class="col-sm-6">
            <input type="password" name="password" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-6">
            <button type="submit" class="btn btn-info">Login</button>
          </div>
        </div>
      </form>

      <h2>Registration</h2>
      <form class="form-horizontal" action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="first_name" class="col-sm-2 control-label">First Name</label>
          <div class="col-sm-6">
            <input type="text" name="first_name" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <label for="last_name" class="col-sm-2 control-label">Last Name</label>
          <div class="col-sm-6">
            <input type="text" name="last_name" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <label for="email_address" class="col-sm-2 control-label">Email Address</label>
          <div class="col-sm-6">
            <input type="email" name="email_address" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <label for="password" class="col-sm-2 control-label">Password</label>
          <div class="col-sm-6">
            <input type="password" name="password" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <label for="confirm_password" class="col-sm-2 control-label">Confirm Password</label>
          <div class="col-sm-6">
            <input type="password" name="confirm_password" class="form-control">
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-6">
            <button type="submit" class="btn btn-info">Register</button>
          </div>
        </div>
      </form>
    </div>
  </body>
</html>

django/python_beltreview/apps/login/templates/login/success.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Reg | Success</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
        <h3>{{message}}</h3>
      {% endfor %}
    {% endif %}
    <h2>Hello, {{request.session.first_name}}!</h2>
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Log Out">
    </form>
  </body>
</html>