django/UserDashboard/UserDashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^LogReg', include('apps.LogReg.urls', namespace='logreg')),
]

django/UserDashboard/apps/LogReg/urls.py
#LogReg
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register$', views.log_reg, name="register"),
    url(r'^login$', views.log_reg, name="login"),
    url(r'^logout$', views.logout, name="logout"),
]

#if we have the same views.method do we use the same name?
#what is the difference between using a regex with the $ at the end and not?

django/UserDashboard/apps/dashboard/urls.py
#dashboard
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register', views.registration, name='registration'),
    url(r'^sign_in', views.sign_in, name='sign_in'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^show/(?P<id>\d+)/$', views.show, name='show'),
    url(r'^hide', views.hide, name='hide'),
    url(r'^users/new', views.new_user, name='new_user'),
    url(r'^users/add', views.add_user, name='add_user'),
    url(r'^users/edit/(?P<id>\d+)/$', views.edit_admin, name='edit_admin'),
    url(r'^users/edit/info/(?P<id>\d+)/$', views.edit_info, name='edit_info'),
    url(r'^users/edit/password/(?P<id>\d+)/$', views.edit_password, name='edit_password'),
    url(r'^users/edit', views.profile, name='profile'),
    url(r'^users/edit/description/(?P<id>\d+)/$', views.edit_description, name='edit_description'),
    url(r'^users/show/(?P<id>\d+)/$', views.show_user, name='show_user'),
    url(r'^message/(?P<owner_id>\w+)*$', views.message, name='message'),
    url(r'^comment/(?P<owner_id>\w+)*/(?P<message_id>\d+)*$', views.comment, name='comment'),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
]

django/UserDashboard/apps/dashboard/models.py
#dashboard
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from ..LogReg.models import userDB

# Create your models here.
class messageManager(models.Manager):
    def message_check(self, data, owner_id, author):
        errors = []
        if len(data['message']) < 1:
            errors.append('message', 'Message must be entered.')

        if errors:
            return [False, errors]
        else:
            #author will be in session and can be passed in from views
            #owner_id will be passed into the url
            owner = userDB.objects.get(id=owner_id)
            newMessage = Message.objects.create(message=data['message'], author=author, owner=owner)
            return [True]

class commentManager(models.Manager):
    def comment_check(self, data, owner_id, author, message_id):
        errors = []
        if len(data['comment']) < 1:
            errors.append('comment', 'Comment must be entered.')

        if errors:
            return [False, errors]
        else:
            #author will be in session and can be passed in
            #owner_id and message_id will be passed into the url
            owner = userDB.objects.get(id=owner_id)
            message = Message.objects.get(id=message_id)
            newComment = Comment.objects.create(comment=data['comment'], author=author, owner=owner, message=message)
            return [True]

class Message(models.Model):
    message = models.TextField()
    author = models.ForeignKey(userDB, related_name='message_author')
    owner = models.ForeignKey(userDB, related_name='message_owner')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = messageManager()

class Comment(models.Model):
    comment = models.TextField()
    message = models.ForeignKey(Message, related_name='comment_message')
    author = models.ForeignKey(userDB, related_name='comment_author')
    owner = models.ForeignKey(userDB, related_name='comment_owner')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = commentManager()

django/UserDashboard/apps/dashboard/views.py
#dashboard
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from ..LogReg.models import userDB
from .models import Message, Comment
# Create your views here.

#displays home page
def home(request):
    return render(request, 'dashboard/home.html')

#displays registration page
def registration(request):
    return render(request, 'dashboard/registration.html')

#displays log in page
def sign_in(request):
    return render(request, 'dashboard/sign_in.html')

#determines if user is admin or not then displays appropriate dashboard page
def dashboard(request):
    context = {
        'users': userDB.objects.all(),
        'remove': False,
    }
    if request.session['user']['user_level'] == 'admin':
        return render(request, 'dashboard/dashboard_admin.html', context)
    else:
        return render(request, 'dashboard/dashboard.html', context)

#shows a confirmation div on the admin dashboard before removing a user
def show(request, id):
    context = {
        'users': userDB.objects.all(),
        'remove': True,
        'del_user': userDB.objects.get(id=id)
    }
    return render(request, 'dashboard/dashboard_admin.html', context)

#hides confirmation div on the admin dashboard
def hide(request):
    context = {
        'users': userDB.objects.all(),
        'remove': False,
    }
    return render(request, 'dashboard/dashboard_admin.html', context)


#confirms admin is attempting to remove then removes user whose id has been passed in through urls
def remove(request, id):
    if request.session['user']['user_level'] == 'admin':
        userDB.objects.get(id=id).delete()
        return redirect('dashboard:dashboard')

#confirms admin is attempting to access then displays create new user page
def new_user(request):
    if request.session['user']['user_level'] == 'admin':
        return render(request, 'dashboard/new.html')
    else:
        return redirect('dashboard:dashboard')

#add new user method
def add_user(request):
    if request.method == 'POST':
        print "attempting to add a new user"
        response = userDB.objects.check_create(request.POST)
        if not response[0]:
            print 'error!'
            for error in response[1]:
                messages.error(request, error[1])
            return redirect('dashboard:new_user')
    return redirect('dashboard:dashboard')

#confirms admin is attempting to access then displays admin edit page for user with id
def edit_admin(request, id):
    if request.session['user']['user_level'] == 'admin':
        context = {
            'user': userDB.objects.get(id=id)
        }
        return render(request, 'dashboard/edit_admin.html', context)
    return redirect('dashboard:dashboard')

#validates information and updates user accordingly
def edit_info(request, id):
    if request.method == 'POST':
        response = userDB.objects.check_info_edit(request.POST, id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
            if request.POST['page'] == 'admin':
                return redirect('dashboard:edit_admin', id=id)
            else:
                return redirect('dashboard:profile')
    return redirect('dashboard:dashboard')

#validates password and pswd conf then updates user accordingly
def edit_password(request, id):
    if request.method == 'POST':
        response = userDB.objects.check_pwd_edit(request.POST, id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
            if request.POST['page'] == 'admin':
                return redirect('dashboard:edit_admin', id=id)
            else:
                return redirect('dashboard:edit_profile')
    return redirect('dashboard:dashboard')

#validates description then updates user
def edit_description(request, id):
    if request.method == 'POST':
        response = userDB.objects.check_desc_edit(request.POST, id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
                return redirect('dashboard:edit_profile')
                return redirect('dashboard:dashboard')

#display profile page for user if there is a user in session
def profile(request):
    if 'user' in request.session:
        return render(request, 'dashboard/profile.html')
    return redirect('dashboard:home')

#display user page with their messages and comments
def show_user(request, id):
    owner = userDB.objects.get(id=id)
    context = {
        'owner': owner,
        'all_messages': Message.objects.filter(owner=owner),
        'comments': Comment.objects.filter(owner=owner),
    }
    return render(request, 'dashboard/user.html', context)

def message(request, owner_id):
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Message.objects.message_check(request.POST, owner_id, author)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
    return redirect('dashboard:show_user', id=owner_id)

def comment(request, owner_id, message_id):
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Comment.objects.comment_check(request.POST, owner_id, author, message_id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
    return redirect('dashboard:show_user', id=owner_id)

django/UserDashboard/apps/dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <a href="{% url 'dashboard:profile' %}">Profile</a>
      </div>
      <div class="right">
        <a href="{% url 'logreg:logout' %}">Log off</a>
      </div>
    </nav>
    <h2>All Users</h2>
    <table>
      <thead>
        <th>ID</th>
        <th>Name</th>
        <th>email</th>
        <th>created_at</th>
        <th>user_level</th>
      </thead>
      <tbody>
      {% for user in users %}
        <tr>
          <td>{{user.id}}</td>
          <td><a href="{% url 'dashboard:show_user' user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          <td>{{user.user_level}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/dashboard_admin.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Admin Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <a href="{% url 'dashboard:profile' %}">Profile</a>
      </div>
      <div class="right">
        <a href="{% url 'logreg:logout' %}">Log off</a>
      </div>
    </nav>
    <div class="top">
      <h2>Manage Users</h2>
      <button type="button" name="button"><a href="{% url 'dashboard:new_user' %}">Add new</a></button>
    </div>
    <table>
      <thead>
        <th>ID</th>
        <th>Name</th>
        <th>email</th>
        <th>created_at</th>
        <th>user_level</th>
        <th>actions</th>
      </thead>
      <tbody>
      {% for user in users %}
        <tr>
          <td>{{user.id}}</td>
          <td><a href="{% url 'dashboard:show_user' user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          <td>{{user.user_level}}</td>
          <td><a href="{% url 'dashboard:edit_admin' user.id %}">edit</a>  <a href="{% url 'dashboard:show' user.id %}">remove</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% if remove %}
      <div id="confirmation">
        <h3>Are you sure you want to remove this user?</h3>
          <a class="remove_link" href="{% url 'dashboard:remove' del_user.id %}">Yes. Remove User</a>
          <a class="remove_link" href="{% url 'dashboard:hide' %}">No</a>
      </div>
      {% endif %}
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/edit_admin.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit User</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <a href="{% url 'dashboard:profile' %}">Profile</a>
      </div>
      <div class="right">
        <a href="{% url 'logreg:logout' %}">Log off</a>
      </div>
    </nav>
    <div class="top">
      <h2>Edit user # {{user.id}}</h2>
      <button type="button" name="button"><a href="{% url 'dashboard:dashboard' %}">Return to Dashboard</a></button>
    </div>
    <div id="flash_messages">
      {% if messages %}
        {% for message in messages %}
          <p class="error">{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
    <div class="edit_info">
      <p class='title'>Edit Information</p>
      <form action="{% url 'dashboard:edit_info' user.id %}" method="post">
        {% csrf_token %}
        <p>Email Address:</p>
        <input type="text" name="email" placeholder="{{user.email}}">
        <p>First Name:</p>
        <input type="text" name="first_name" placeholder="{{user.first_name}}">
        <p>Last Name:</p>
        <input type="text" name="last_name" placeholder="{{user.last_name}}">
        <p>User Level</p>
        <select name='user_level'>
          <option value='normal'>Normal</option>
          <option value="admin">Admin</option>
        </select>
        <button type="submit" name="page" value="admin">Save</button>
      </form>
    </div>
    <div class="change_password">
      <p class='title'>Change Password</p>
      <form action="{% url 'dashboard:edit_password' user.id %}" method="post">
        {% csrf_token %}
        <p>Password:</p>
        <input type="password" name="password" placeholder="*********">
        <input type="password" name="password_confirmation" placeholder="*********">
        <button type="submit" name="page" value="admin">Update Password</button>
      </form>
    </div>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:home' %}">Home</a>
      </div>
      <div class="right">
        <a href="{% url 'dashboard:sign_in' %}">Sign In</a>
      </div>
    </nav>
    <h1>Welcome to the Dashboard! Let's get started.</h1>
    <button type="button" name="button"><a href="{% url 'dashboard:sign_in' %}">Start</a></button>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New User</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <a href="{% url 'dashboard:profile' %}">Profile</a>
      </div>
      <div class="right">
        <a href="{% url 'logreg:logout' %}">Log off</a>
      </div>
    </nav>
    <div class="top">
      <h2>Add a new user</h2>
      <button type="button" name="button"><a href="{% url 'dashboard:dashboard' %}">Return to Dashboard</a></button>
    </div>
    <div id="flash_messages">
      {% if messages %}
        {% for message in messages %}
          <p class="error">{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
    <form action="{% url 'dashboard:add_user' %}" method="post">
      {% csrf_token %}
      <p>Email Address:</p>
      <input type="email" name="email" placeholder="email">
      <p>First Name:</p>
      <input type="text" name="first_name" placeholder="First Name">
      <p>Last Name:</p>
      <input type="text" name="last_name" placeholder="Last Name">
      <p>Password must be at least 8 characters.</p>
      <input type="password" name="password" placeholder="password ********">
      <p>Password Confirmation</p>
      <input type="password" name="password_confirmation" placeholder="password confirmation">
      <button class="btn btn-info" type="submit">Create</button>
    </form>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <a href="{% url 'dashboard:profile' %}">Profile</a>
      </div>
      <div class="right">
        <a href="{% url 'logreg:logout' %}">Log off</a>
      </div>
    </nav>
    <h2>Edit Profile</h2>
    <div id="flash_messages">
      {% if messages %}
        {% for message in messages %}
          <p class="error">{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
    <div class="edit_info">
      <p class='title'>Edit Information</p>
      <form action="{% url 'dashboard:edit_info' request.session.user.id %}" method="post">
        {% csrf_token %}
        <p>Email Address:</p>
        <input type="text" name="email" placeholder="{{request.session.user.email}}">
        <p>First Name:</p>
        <input type="text" name="first_name" placeholder="{{request.session.user.first_name}}">
        <p>Last Name:</p>
        <input type="text" name="last_name" placeholder="{{request.session.user.last_name}}">
        <button type="submit" name="page" value="normal">Save</button>
      </form>
    </div>
    <div class="change_password">
      <p class='title'>Change Password</p>
      <form action="{% url 'dashboard:edit_password' request.session.user.id %}" method="post">
        {% csrf_token %}
        <p>Password:</p>
        <input type="password" name="password" placeholder="*********">
        <input type="password" name="password_confirmation" placeholder="*********">
        <button type="submit" name="page" value="normal">Update Password</button>
      </form>
    </div>
    <p>Edit descrption</p>
    <form action="{% url 'dashboard:edit_description' request.session.user.id %}" method="post">
      {% csrf_token %}
      <textarea name="description" rows="8" cols="80">{{request.session.user.description}}</textarea>
      <button type="submit" name="page" value="normal">Save</button>
    </form>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/registration.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:home' %}">Home</a>
      </div>
      <div class="right">
        <a href="{% url 'dashboard:sign_in' %}">Sign In</a>
      </div>
    </nav>
    <h2>Register</h2>
    <div id="flash_messages">
      {% if messages %}
        {% for message in messages %}
          <p class="error">{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
      <form action="{% url 'logreg:register' %}" method="post">
        {% csrf_token %}
        <input type="text" name="first_name" placeholder="First Name">
        <input type="text" name="last_name" placeholder="Last Name">
        <input type="email" name="email" placeholder="email">
        <p>Password must be at least 8 characters.</p>
        <input type="password" name="password" placeholder="password ********">
        <input type="password" name="password_confirmation" placeholder="password confirmation">
        <button class="btn btn-info" type="submit" id="register_button" name="attempt" value="register">Register</button>
      </form>
      <footer>
        <a href="{% url 'dashboard:sign_in' %}">Already have an account? Login</a>
      </footer>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/sign_in.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sign In</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:home' %}">Home</a>
      </div>
      <div class="right">
        <a href="{% url 'dashboard:sign_in' %}">Sign In</a>
      </div>
    </nav>
    <h2>Sign In</h2>
    <div id="flash_messages">
      {% if messages %}
        {% for message in messages %}
          <p class="error">{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
    <form action="{% url 'logreg:login' %}" method="post">
      {% csrf_token %}
      <input type="email" name="email" placeholder="email">
      <input type="password" name="password" placeholder="password *********">
      <button class="btn btn-info" type="submit" name='attempt' value='login'>Log In</button>
    </form>
    <a href="{% url 'dashboard:registration' %}">Don't have an account? Register.</a>
  </body>
</html>

django/UserDashboard/apps/dashboard/templates/dashboard/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Information</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
  </head>
  <body>
    <nav>
      <div class="left">
        <h2>Test App</h2>
        <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
        <a href="{% url 'dashboard:profile' %}">Profile</a>
      </div>
      <div class="right">
        <a href="{% url 'logreg:logout' %}">Log off</a>
      </div>
    </nav>
    <!-- user info then messages-->
    <h2>{{owner.first_name}} {{owner.last_name}}</h2>
    <table>
      <tbody>
        <tr>
          <td>Registered at: </td>
          <td>{{owner.created_at}}</td>
        </tr>
        <tr>
          <td>User ID:</td>
          <td>#{{owner.id}}</td>
        </tr>
        <tr>
          <td>Email address:</td>
          <td>{{owner.email}}</td>
        </tr>
        <tr>
          <td>Description: </td>
          <td>{{owner.description}}</td>
        </tr>
      </tbody>
    </table>
    <h2>Leave a message for {{owner.first_name}}</h2>
    <div id="flash_messages">
      {% if messages %}
        {% for message in messages %}
          <p class="error">{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
    <form action="{% url 'dashboard:message' owner_id=owner.id %}" method="post">
      {% csrf_token %}
      <textarea name="message" rows="8" cols="80"></textarea>
      <button type="submit" name="button">Post</button>
    </form>
    {% for message in all_messages %}
    <div class="label">
      <a href="{% url 'dashboard:show_user' message.author.id %}" class='label_left'>{{message.author.first_name}} {{message.author.last_name}}</a>
      <p class="label_right">{{message.created_at|timesince}} ago</p>
    </div>
    <div class="message">
      <p>{{message.message}}</p>
      {% for comment in comments %}
      <div class="comments">
        {% if message.id == comment.message.id %}
        <div class="label">
          <a href="{% url 'dashboard:show_user' message.author.id %}">{{comment.author.first_name}} {{comment.author.last_name}}</a>
          <p class="label_right">{{comment.created_at|timesince}} ago</p>
        </div>
        <div class="comment">
          <p>{{comment.comment}}</p>
        </div>
        {% endif %}
      </div>
      {% endfor %}
      <div id="flash_messages">
        {% if messages %}
          {% for message in messages %}
            <p class="error">{{message}}</p>
          {% endfor %}
        {% endif %}
      </div>
      <form action="{% url 'dashboard:comment' owner_id=owner.id message_id=message.id %}" method="post">
        {% csrf_token %}
        <textarea name="comment" rows="4" cols="80">write a message here</textarea>
        <button type="submit" name="button">Post</button>
      </form>
    </div>
    {% endfor %}
  </body>
</html>